Fixed identation and file eslint
Laboratoria-learning/valid-credit-card pull request #38
Opened 2017-11-07 17:51 UTC by Danielapariona

2017-11-08 22:10 UTC, developerVilchez commented
@diegovelezg este pull request pasa.

2017-12-16 17:31 UTC, xaro requested changes
Muy buen uso de comentarios en el código!

Muy bien organizado el código, felicitaciones, es muy fácil de entender.

Agregué unos comentarios pero en general el código está muy bien.

2017-12-16 17:31 UTC, xaro commented on js/app.js
> +  var strNum = numCard.toString();
El nombre `strNum` es poco descriptivo. Trata de que tus variables expliquen "que" es lo que contienen, no el tipo de variable que son.
En este caso, algo como `numCardStr` or `numCardAsString` seria mas adecuado.

2017-12-16 17:31 UTC, xaro commented on js/app.js
> +      var result;
La variable `result` nunca es usada, puede ser eliminada.

2017-12-16 17:31 UTC, xaro commented on js/app.js
> +  for (var i = 1; i < arrayReverse.length - 1; i++) {
Este `for` irá de 1 al 14 (`i < 15`), por lo que no considera el último dígito. `i <= arrayReverse.length` servirá en este caso para recorrer el arreglo completo.
En general, si `i` comienza en 0, `i < array.length` o `i <= array.length - 1` es correcto para recorrer el entero. Si `i` comienza en 1, `i <= array.length` es correcto.

2017-12-16 17:31 UTC, xaro commented on js/app.js
> +  var state;
Esta variable es innecesaria ya que sólo la usas para retornar en la línea siguiente.

Podrías hacer `return (sum % 10 === 0 ? 'válida' : 'inválida';`

2017-12-16 17:31 UTC, xaro commented on js/app.js
> +  var state;
Esta variable `state` nunca es usada, y puede ser eliminada.

2017-12-16 17:31 UTC, xaro commented on js/app.js
> +  if (numCard.length === 16) {
Esta validación debería estar dentro de la función isValidCard ya que es bueno validar en todos los usos de la función.

2017-12-16 17:31 UTC, xaro commented on js/app.js
> +  } else if (numCard === '' || numCard.length !== 16) {
Este `else if` es innecesario ya que `else` es suficiente (si `numCard.length` no es 16, el string no estará vacío).

2022-05-20 05:09 UTC, closed without merging